Repository BinaryStudioAcademy/bsa-winter-2022-look, pull requests merged in 2022-02, with the labels that each got.

#9 Feature/add all models
  backend/app/Models/Event.php
  backend/app/Models/EventType.php
  backend/app/Models/Location.php
  backend/app/Models/Match.php
  backend/app/Models/Role.php
  backend/app/Models/User.php
  backend/app/Models/UserInterest.php
  backend/app/Models/UserMedia.php
  backend/app/Models/UserParameter.php
  backend/app/Models/UserSetting.php
Labels: enhancement

#25 'Reset password' and 'change password' implementation
  frontend/src/bundles/auth/components/ChangePasswordForm.vue
  frontend/src/bundles/auth/components/LoginForm.vue
  frontend/src/bundles/auth/components/ResetPasswordForm.vue
  frontend/src/bundles/auth/pages/ChangeEmailPasswordPage.vue
  frontend/src/bundles/auth/pages/ChangePasswordPage.vue
  frontend/src/bundles/auth/pages/ResetPasswordPage.vue
  frontend/src/bundles/auth/routes.ts
  frontend/src/bundles/auth/store/modules/auth/actions.ts
  frontend/src/bundles/auth/store/modules/auth/types/actions.ts
  frontend/src/bundles/common/repository/contracts/UserRepository.ts
  frontend/src/bundles/common/repository/http/HttpUserRepository.ts
  frontend/src/bundles/common/repository/requests/ChangePasswordRequest.ts
  frontend/src/plugins/veeValidate.ts
Labels: enhancement

#37 Deleted header from main page
  frontend/src/bundles/home/components/Header.vue
  frontend/src/bundles/home/pages/HomePage.vue
Labels: bug

#39 Remove 'v1' prefix from user route
  backend/routes/api.php
Labels: bug

#40 Fix change password request
  frontend/src/bundles/auth/components/ChangePasswordForm.vue
  frontend/src/bundles/common/repository/http/HttpUserRepository.ts
  frontend/src/bundles/common/repository/requests/ChangePasswordRequest.ts
Labels: bug

#41 Added redirect on list page after login
  frontend/src/bundles/auth/pages/LoginPage.vue
Labels: bug, enhancement

#44 Change field name for displaying validation errors in 'name'
  frontend/src/bundles/auth/components/SetUpForm.vue
Labels: enhancement

#42 Custom response for all validation errors
  backend/app/Exceptions/Handler.php
Labels: enhancement

#43 Add error messages for 'register-user' validation errors
  backend/app/Http/Requests/Auth/RegisterHttpRequest.php
Labels: enhancement

#45 Add custom scrollbar to all project
  frontend/src/assets/scss/override.scss
Labels: enhancement
