Repository BinaryStudioAcademy/bsa-winter-2022-look, pull requests merged in 2022-03, with the labels that each got.

#46 Fix show validation error if user is not in database
  backend/app/Http/Requests/Api/Auth/ForgotPasswordRequest.php
Labels: bug

#47 Feature/add roles
  backend/app/Models/Role.php
  backend/app/Models/User.php
  backend/app/Policies/EventPolicy.php
  backend/app/Providers/AuthServiceProvider.php
  backend/database/migrations/2022_02_16_114717_add_role_id_to_users_table.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/RolesTableSeeder.php
  backend/database/seeders/UsersTableSeeder.php
Labels: enhancement

#50 Email validation after user registered - frontend
  backend/resources/views/email/email_verification.blade.php
  frontend/src/bundles/auth/pages/EmailConfirmPage.vue
  frontend/src/bundles/auth/pages/EmailValidationRequestPage.vue
  frontend/src/bundles/auth/pages/RegisterMediaPage.vue
  frontend/src/bundles/auth/pages/RegisterSetUpPage.vue
  frontend/src/bundles/auth/routes.ts
  frontend/src/bundles/auth/store/modules/auth/actions.ts
  frontend/src/bundles/auth/store/modules/auth/types/actions.ts
  frontend/src/bundles/common/repository/contracts/UserRepository.ts
  frontend/src/bundles/common/repository/http/HttpUserRepository.ts
Labels: enhancement

#52 Fix email validation template
  backend/resources/views/email/email_verification.blade.php
Labels: bug

#54 Fixed bugs in field about yourself
  frontend/src/bundles/auth/components/AdditionalForm.vue
  frontend/src/bundles/auth/components/SetUpForm.vue
  frontend/src/plugins/veeValidate.ts
Labels: bug

#55 Fixed validate phone field
  frontend/src/bundles/auth/components/AdditionalForm.vue
  frontend/src/plugins/veeValidate.ts
Labels: bug

#56 Fixed double scroll on login, singin and register pages
  frontend/src/bundles/auth/pages/LayoutPage.vue
Labels: bug

#63 Fixed styles resset password form
  frontend/src/bundles/auth/components/ChangePasswordForm.vue
  frontend/src/bundles/auth/components/ResetPasswordForm.vue
Labels: bug

#65 Added age selector in register layout
  frontend/src/bundles/auth/components/AdditionalForm.vue
Labels: bug, enhancement

#81 Fixed styles on registration page
  frontend/src/bundles/auth/components/AdditionalForm.vue
  frontend/src/bundles/auth/pages/LayoutPage.vue
Labels: bug

#78 Fixed appearing message for non-existent email address in DB
  backend/app/Http/Requests/Api/Auth/LoginHttpRequest.php
Labels: bug

#82 Fixed toolbar-link styles on setting page
  frontend/src/bundles/main/components/TabsComponent.vue
Labels: bug

#76 Fixed erroe-message visibility under location field
  frontend/src/bundles/main/components/UserDetailsForm.vue
Labels: bug

#80 Fixed min age - 18
  frontend/src/bundles/auth/components/AdditionalForm.vue
Labels: bug

#77 Deleted lift of scrollbar, fixed width scroll like in figma design
  frontend/src/assets/scss/override.scss
Labels: bug

#85 Fixed styles on register and login pages
  frontend/src/bundles/auth/pages/LayoutPage.vue
Labels: bug

#87 Added logout logic
  frontend/src/bundles/auth/store/modules/auth/actions.ts
  frontend/src/bundles/auth/store/modules/auth/types/actions.ts
  frontend/src/bundles/common/repository/contracts/UserRepository.ts
  frontend/src/bundles/common/repository/http/HttpUserRepository.ts
  frontend/src/bundles/main/components/NavbarComponent.vue
Labels: enhancement

#86 Fixed overflow scroll appearing in fields hobbies and interests
  backend/.gitignore
  frontend/src/assets/scss/override.scss
Labels: bug

#89 Fixed DB users
  backend/database/migrations/2014_10_12_000000_create_users_table.php
  backend/database/migrations/2022_03_31_220957_add_last_seen_to_users_table.php
Labels: bug
